### ISSUE TITLE
安装完成后, npm全局包找不到了

### ISSUE THREAD

**Issue by brainpoint** [Kenshin/gnvm#11]
在其他项目中无法使用全局包, 是不是哪里的配置被修改; 我查看配置 npm config 的prefix/cache都是正常的,求解?

**Comment by Kenshin** [comment]
全局包的路径加到环境变量里了吗？

**Comment by brainpoint** [comment]
加了, 不可以; 在安装gnvm之前是没问题的;

**Comment by Kenshin** [comment]
估计新的 npm 路径发生了改变，所以之前的全局包找不到了，因此不好使。所以可以这么做：
- 在新的 `npm` 下面重新安装之前的全局包，或者把之前的包复制到新的 `npm` 路径下。

假设还不好使的话，使用 `gnvm uninstall npm` 卸载掉，然后手动配置安装 `npm` 再试试。

---

如果上述操作仍旧不好使的话，是否使用了 `gnvm reg` 用来注册？

> 其他项目中无法使用全局包

具体是什么情况？例如在全局包的命令不好使？
