### ISSUE TITLE
无法选择最新的npm

### ISSUE THREAD

**Issue by Nicklzy** [Kenshin/gnvm#12]
can not find the lastest npm
```
C:\Users\NICK>gnvm npm latest
Notice: local    npm version is 4.0.2
Notice: remote   npm version is 3.10.9
Notice: download 3.10.9 version [Y/n]? n
Notice: operation has been cancelled.
```

**Comment by Kenshin** [comment]
我这边没有问题，请看输出：
```
gnvm npm latest
Notice: local    npm version is 3.8.8
Notice: remote   npm version is 3.10.9
Notice: download 3.10.9 version [Y/n]? Y
Start download new npm version v3.10.9.zip
v3.10.9.zip: 100% [==================================================>] 2s
Start unzip and install v3.10.9.zip zip file, please wait.
Set success, current npm version is 3.10.9.
```

或者看截图
![Imgur](http://i.imgur.com/ADZmvYJ.png)

另外，npm 的源需要切换到 `TAOBAO` 才行，目前 `TAOBAO` 的 npm 源是 `3.10.9`

**Comment by mgcnrx11** [comment]
目前淘宝最新的是4.2，https://npm.taobao.org/mirrors/npm/

但是，gnvm npm latest还是3.10.9

是否改变一下LATNPMURL  = "https://raw.githubusercontent.com/npm/npm/master/package.json"这个地址？分支从master改为latest

**Comment by Kenshin** [comment]
okay，我确认一下，之前 `DEFAULT` 的 `npm` 也有些问题。
到时一起更新，最好把 `url` 做到 `config` 里面，如果有变化的话，可以直接在 `config` 中修改。
