### ISSUE TITLE
gnvm use latest失败

### ISSUE THREAD

**Issue by yybear** [Kenshin/gnvm#14]
报 Waring: 7.3.0 folder is not exist node.exe, use 'gnvm ls' get local Node.js version list. See 'gnvm help ls'.
但是实际上7.30目录下有node.exe

找到原因了是之前install latest 没有下载完全，导致node.exe 不完整

**Comment by Kenshin** [comment]
okay~
`gnvm` 会验证 `node.exe` 的合法性，如果非法的话，即表示不存在当前这个版本，也就是你之前遇到的情况。
