### ISSUE TITLE
gnvm 64位 win7无法安装

### ISSUE THREAD

**Issue by ghost** [Kenshin/gnvm#15]
我是从github源下载的64位。我的系统是win7 64位，但是下载完毕后无法打开gnvm

**Comment by Kenshin** [comment]
需要把 `gnvm 放到 环境变量` 或者 `当前将 cmd 指向 gnvm 所在的目录`，如果还有问题的话，建议你截图。 👍

**Comment by ghost** [comment]
多谢啦！配置了环境变量就OK了。支持作者!!

**Comment by Kenshin** [comment]
okay 搞定就好。
另外，当为默认库时 `gnvm npm latest` 有 bug，不过，这个 bug 可以绕过。详情请看 https://github.com/Kenshin/gnvm/issues/6

**Comment by JameJJ** [comment]
66666膜拜膜拜
