### ISSUE TITLE
Mac os 咋办？

### ISSUE THREAD

**Issue by ruoduan-hub** [Kenshin/gnvm#29]
如上

**Comment by ruoduan-hub** [comment]
只能用nvm了 :grin:

**Comment by Kenshin** [comment]
嗨，不好意思，前几天在休假。

Mac OS 下有很多优秀的产品，所以当初只做了 Win 下面的。

**Comment by houfeng0923** [comment]
@Kenshin ，想了解下，这个相比 nvm，启动速度等方面有没有优势？是否考虑兼容macos？

**Comment by Kenshin** [comment]
@houfeng0923 

功能和配置项上应该优于 `nvm` 
`启动速度` 不是很清楚，没有比较过，应该也无需介怀它们的启动速度吧。

不会考虑兼容 `Mac OS` 因为没必要，Linux 上有许多优秀的前辈了。（ 即便跨平台是很容易做到的，毕竟 Golang 的程序
