### ISSUE TITLE
4.2.1的版本路径好像不一样所以安装不了

### ISSUE THREAD

**Issue by as3long** [Kenshin/gnvm#4]
http://npm.taobao.org/mirrors/node/v4.2.1/win-x64/

**Comment by gitJunz** [comment]
我也遇到这个问题了，希望作者能修改一下~ 
gnvm install http://npm.taobao.org/mirrors/node/v4.2.1/win-x64/node.exe
如果能改成这样的格式就能解决所有问题啦！

**Comment by onvno** [comment]
路径确实有问题，希望能解决

**Comment by Kenshin** [comment]
感谢大家的反馈，下周内搞定这个 `Bug` ，应该是由  `0.xx.xx` 升级至 `4.x.x` 所致！
实在不好意思，这个 `Bug` 拖了这么久。

**Comment by suifengtec** [comment]
额，我使用 DEFAULT ，也没这个版本...

**Comment by Kenshin** [comment]
关于这个 `bug` 是这样形成的：
1. 推荐的七牛的镜像 down 掉了，所以 凡是使用  `gnvm config registry  http://dist.u.qiniudn.com/` 都不行了。
2. 改进第一个问题的办法，使用 `gnvm config registry DEFAULT`
3. 使用 `gnvm install x.xx.xx` 时，会检查 `http://nodejs.org/dist/` 这个目录 以及 `http://nodejs.org/dist/npm-versions.txt` 这个文件，但这个目录的结构发生了改变，所以 `gnvm install x.xx.xx` 无法使用了。但之前 `0.11.11` 之前的版本都可以使用。（ 然并卵... ）

下周（ 2月27日） 之前会解决上述问题 ，并打算新增几个功能，大家有什么好的建议，可以发在这里。
`今天是元宵节，祝大家快乐~ `

**Comment by Kenshin** [comment]
Hi All：
这个 `issues` 的问题 已经解决了。包括：
- gnvm config INIT
- gnvm install x.xx.xx
- gnvm ls -r

下载地址：
<http://ksria.qiniudn.com/gnvm-0.1.4-x64.zip>

**注意：**
上面个下载地址 只针对 64位 系统。

版本升级为：
- `0.1.4 beta` - 之所以是 `beta` 是因为仅仅解决了这个 `issues` 提到的问题。由于时间限制，也只打包了 x64 的版本。
- `0.1.5` - 会加入一些新的功能。

下载此版本后，请覆盖之前的版本，执行：
- `gnvm config registry TAOBAO` 重新设置 registry

  > `0.1.4` 内置了 `http://npm.taobao.org/mirrors/node` 关键字 `TAOBAO`。

**Comment by Kenshin** [comment]
`x86` 版本已经可以下载：
<http://ksria.qiniudn.com/gnvm-0.1.4-x64.zip>

`0.1.5` 正在开发中，下周有可能发，我将关闭此 `issues` 。

**Comment by Kenshin** [comment]
version `0.2.0` 正式提供下载，增加了：
- Add new feature `gnvm session` Use any Node.js version of the local already exists version by current session.
- Add new feature `gnvm npm`     NPM version management.
- Add new feature `gnvm search`  Search and Print Node.js version detail usage wildcard mode or regexp mode.
- Add new feature `gnvm reg`     Add config property `noderoot` to Environment variable `NODE_HOME`.
- Add new `gnvm` icon, inlcude:  `32*32`, `64*64`, `128*128` size.
- Senior  feature `gnvm ls`      Add detail print, e.g. `gnvm ls -r -d -l`.
- Senror  feature `gnvm config`  Add print all property`gnvm config` and test custom registry `gnvm config registry test`.
- Senior  feature `gnvm config`  built-in `DEFAULT` http://nodejs.org/dist/ and `TAOBAO` http://npm.taobao.org/mirrors/node keywords.
- Senior  feature `gnvm install` Auto support iojs, e.g. `gnvm install 1.0.0` and arch, e.g. `gnvm install 5.1.1-x64 5.1.1-x86`.
- Senior  feature `gnvm version` Add new flag `-r`, print `CHANGELOG`, e.g. `gnvm version -r -d`.

具体使用方式可以看 `master branch` 的 `README.md`
