### ISSUE TITLE
用gnvm安装npm后原来的模块找不到了

### ISSUE THREAD

**Issue by zh-impact** [Kenshin/gnvm#8]
用 npm ls 看不到以前安装的包了，
并且打印 module.paths 也不正确了

记得以前的modules不是在nodejs的安装目录的。
现在定位到nodejs\node_modules下了，
这个是gnvm做出的改变呢？还是npm？
怎么修复

**Comment by Kenshin** [comment]
请问你使用了哪些命令？
仅仅是 `gnvm npm install` 的话，
会找到之前的npm 路径，并且安装，否则的话安装到 `Node.js` 所在的文件夹，但不会删除 其它 `npm` 的包。
解决办法：把之前的 npm modules 里面的包 复制到 当前文件夹 即可。

**Comment by zh-impact** [comment]
之前的模块都在 `C:\Users\Administrator\AppData\Roaming\npm\node_modules` 里面，可以继续调用。npm ls -g 定位到nodejs了。
**现在的问题**是安装新的包失败，提示 Administrator 权限问题，我通过管理员shell安装还是提示权限问题

**Comment by Kenshin** [comment]
这不应该，或许跟你 `OS` 的权限配置有关...  但你可以使用如下的方式：
- 使用 `npm prefix -g` 查看 `npm install -g` 时安装的目录；
- 使用 `npm config set prefix  C:\Users\Administrator\AppData\Roaming\npm\node_modules` 将 `prefix` 重新定义到 之前的目录，然后再试试。

**Comment by zh-impact** [comment]
多谢，解决了

**Comment by Kenshin** [comment]
okay，解决就好！
Tips：`npm` 的路径与 `npm modules` 的路径不一致，请留意～
