### ISSUE TITLE
无法安装node

### ISSUE THREAD

**Issue by aOrz** [Kenshin/gnvm#9]
`gnvm install`没有反应

**Comment by aOrz** [comment]
已经更换了淘宝的源

**Comment by Kenshin** [comment]
更换 `淘宝源` 后，还有问题吗？没有的话，请关闭这个 `issues` 。

**Comment by aOrz** [comment]
还是有问题，没有反应，node安装目录下只是多了了要安装版本的文件夹，里面的node只有几k

**Comment by Kenshin** [comment]
下载失败一般是网络环境较差造成的，多试几次吧。
或者换个网络环境，再试试。

**Comment by aOrz** [comment]
基本上可以排除是网络问题

**Comment by Kenshin** [comment]
仅仅是你之前说的情况，大多是网络环境造成。
否则的话，最好告知你使用了哪些命令，截图，CLI端，系统环境。
